### PR TITLE
Enable\Disable Module, and Announce feature

### PR DESCRIPTION
**Pull request by dunjeon**
Enable\Disable Module, and Announce feature
* set in configuration file

### CODE REVIEW

**Comment by BarbzYHOOL** [comment]
Thank you

Though there is now a new way to make configuration file, maybe check the skeleton module

**Comment by dunjeon** [comment]
Understood. feel free to close and I will re-tool when I get a few moments

**Comment by BarbzYHOOL** [comment]
the new way is probably easier, tell me if it requires us to write a small tutorial maybe

https://github.com/azerothcore/azerothcore-wotlk/commit/d29a1a330018b89ee608aa27e500068f5310ed2a

**Comment by dunjeon** [comment]
I'm gong to wait  for #985 
https://github.com/azerothcore/azerothcore-wotlk/pull/985/commits/da0bada5e50bb6a26ce0ff87972fe9553202f978

**Comment by BarbzYHOOL** [comment]
I can merge it, it will be better than none

**Comment by dunjeon** [comment]
Sorry, I have not had the chance to update to the new style, but this one works well as intended.

**Comment by BarbzYHOOL** [comment]
Ok merged anyway thank you!!

**Pull request merged**
