### PR TITLE
Adding multi-language, starting with Spanish.

### PR DESCRIPTION
**Pull request by pangolp**
Good night, the idea is simple. Using the configuration file, choose the language in which you want to display the messages and then the module will display the messages in that language. Of course, the texts of the other languages have to be added. Hopefully they like the idea, because if so, it would continue with the rest of the modules. Maybe the code could be improved, the only way I could think of. I don't think it should produce any errors.

### CODE REVIEW

**Comment by Helias** [comment]
I like the idea, but we can use gettext/po files to follow a standard and apply in our core the multi-lang

like with https://github.com/cbeck88/spirit-po

**Comment by BarbzYHOOL** [comment]
the strings should be in a separate file dedicated to translation

**Comment by pangolp** [comment]
Perfect, we'll find a way to do it in external files. At the moment, I couldn't really think of anything.

**Comment by BarbzYHOOL** [comment]
in fact it's hard to do, we could also use the existing string tables for that and get the strings from the db (like mod-transmog does)

it's really not easy to think of a good solution imo (which should be a general solution for all modules in top of that)

**Pull request closed without merging**
